// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 0,
      nombre: "Ing. Renato Ponciano",
      introduccion:
        "Profesor e investigador de la USAC, Doctor en ciencias sociales por la Universidad de Padua, Italia, Máster por la Universidad de Maastricht, Holanda, Premio a la Excelencia Académica como profesor de postgrado 2020, USAC.",
      image: "/images/candidatos/1.png",
      descripcion:
        "Renato Ponciano es ingeniero químico graduado de la Universidad de San Carlos de Guatemala (USAC).   Tiene dos maestrías, la primera en Estudios Europeos sobre Sociedad, Ciencia y Tecnología de la Universidad de Maastricht en Holanda; y la segunda en Tecnologías Innovadoras a base de Membranas para el Tratamiento de Agua de la Universidad de Génova, Italia;  allí fue parte del equipo de investigación de dicha Universidad y de la compañía italiana AMGA StA para el montaje de una planta de tratamiento de aguas servidas del tipo MBR. Es Doctor en Ciencias Sociales por la Universidad de Padua, Italia.  En su doctorado prosiguió su estudio de los problemas de Ciencia, Tecnología y Sociedad, enfocándose en su tesis en la aplicación de métodos cuantitativos para el estudio de la representación pública de los conflictos ambientales en Guatemala.Actualmente se desempeña como Profesor Titular en el Departamento de Matemática, donde ocupa el puesto de Jefe del Área Matemática Básica y hasta 2022, en la Escuela de Postgrado de la Facultad de Ingeniería de la USAC, que le otorgó en 2020 el Premio a la Excelencia Académica como docente-investigador. Ha asesorado numerosas tesis a nivel pre-grado y postgrado. Además, es el responsable del diseño e implementación del curso “Separaciones por medio de membranas selectivas, IQ-7”, que desde 2007 se imparte en la Escuela de Ingeniería Química de la FIUSAC y que él mismo impartió hasta 2014. Ha presentado ponencias sobre sus investigaciones en congresos en México, República Dominicana, Colombia, Chile, Suecia, Francia, Austria, Argentina, Italia y Estados Unidos.  Habla fluidamente inglés e italiano.  Participa políticamente porque está convencido que la academia solo puede florecer en una universidad libre de las mafias que la han cooptado por tantos años.",
      imagenes: [
        " /images/renato/1.png",
        " /images/renato/1.png",
        " /images/renato/1.png",
        " /images/renato/1.png",
      ],
    },

    {
      id: 1,
      nombre: "ING GUILLERMO PUENTE",
      introduccion:
        "INGENIERO ELECTRONICO Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nostrum porro asperiores dicta neque, exercitationem incidunt mollitia sed, nesciunt perferendis eligendi architecto. Reiciendis, quas? Aperiam adipisci repellendus neque expedita sint minima hic velit voluptatum mollitia ipsa accusamus, nobis alias ab tempore repellat incidunt suscipit explicabo voluptatibus cupiditate eius? Soluta, ducimus.dignissimos exercitationem dolorem, illo facilis, praesentium maiores. Ab voluptates sequi error rerum harum! Praesentium totam quas consequatur sed non id tempore pariatur, temporibus quidem delectus fugiat corrupti architecto facere sapiente aliquid sunt modi, voluptates qui velit et. Iure ipsam aspernatur voluptate molestiae qui, nihil est at atque vel consequuntur fugit, veritatis tempore sequi, assumenda suscipit inventore ratione deserunt error quasi voluptatem similique expedita. Modi dolor ipsum numquam nam praesentium, et eaque non excepturi amet accusantium!",
      image: "/images/candidatos/2.png",
      descripcion:
        "GUILLERMO PUENTE ES UN INGENIERO ELECTRONICO ha participado en ha hecho tal....Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel molestias recusandae, ratione explicabo ut, ab in hic dignissimos consequuntur a excepturi nemo iste sunt mollitia similique, tenetur ad quis odit? Ad reprehenderit laboriosam repudiandae, animi, natus tempora expedita ducimus officia, quibusdam illum quae esse repellat quas vitae commodi dolores id perferendis odio? Doloribus doloremque molestias consectetur pariatur, corporis perspiciatis nulla ad incidunt beatae cupiditate minus ipsa porro ab laborum adipisci maiores earum dolores quod, id inventore explicabo aut! Iure sint labore, minima suscipit, animi, voluptatibus facilis architecto error rem nemo nobis? Nostrum ea possimus ipsam officiis quia at magnam est labore ipsum minima blanditiis, corrupti eum rerum, architecto asperiores vel cupiditate, modi hic rem. Fugiat fuga esse quo ratione fugit doloribus omnis repellendus veritatis illum dignissimos exercitationem dolorem, illo facilis, praesentium maiores. Ab voluptates sequi error rerum harum! Praesentium totam quas consequatur sed non id tempore pariatur, temporibus quidem delectus fugiat corrupti architecto facere sapiente aliquid sunt modi, voluptates qui velit et. Iure ipsam aspernatur voluptate molestiae qui, nihil est at atque vel consequuntur fugit, veritatis tempore sequi, assumenda suscipit inventore ratione deserunt error quasi voluptatem similique expedita. Modi dolor ipsum numquam nam praesentium, et eaque non excepturi amet accusantium!dignissimos exercitationem dolorem, illo facilis, praesentium maiores. Ab voluptates sequi error rerum harum! Praesentium totam quas consequatur sed non id tempore pariatur, temporibus quidem delectus fugiat corrupti architecto facere sapiente aliquid sunt modi, voluptates qui velit et. Iure ipsam aspernatur voluptate molestiae qui, nihil est at atque vel consequuntur fugit, veritatis tempore sequi, assumenda suscipit inventore ratione deserunt error quasi voluptatem similique expedita. Modi dolor ipsum numquam nam praesentium, et eaque non excepturi amet accusantium!",
    },
    {
      id: 2,
      nombre: "TU ELIGES",
      introduccion:
        "BUSCAMOS UN CANDIDATO Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nostrum porro asperiores dicta neque, exercitationem incidunt mollitia sed, nesciunt perferendis eligendi architecto. Reiciendis, quas? Aperiam adipisci repellendus neque expedita sint minima hic velit voluptatum mollitia ipsa accusamus, nobis alias ab tempore repellat incidunt suscipit explicabo voluptatibus cupiditate eius? Soluta, ducimus.dignissimos exercitationem dolorem, illo facilis, praesentium maiores. Ab voluptates sequi error rerum harum! Praesentium totam quas consequatur sed non id tempore pariatur, temporibus quidem delectus fugiat corrupti architecto facere sapiente aliquid sunt modi, voluptates qui velit et. Iure ipsam aspernatur voluptate molestiae qui, nihil est at atque vel consequuntur fugit, veritatis tempore sequi, assumenda suscipit inventore ratione deserunt error quasi voluptatem similique expedita. Modi dolor ipsum numquam nam praesentium, et eaque non excepturi amet accusantium!",
      image: "/images/candidatos/2.png",
      descripcion:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel molestias recusandae, ratione explicabo ut, ab in hic dignissimos consequuntur a excepturi nemo iste sunt mollitia similique, tenetur ad quis odit? Ad reprehenderit laboriosam repudiandae, animi, natus tempora expedita ducimus officia, quibusdam illum quae esse repellat quas vitae commodi dolores id perferendis odio? Doloribus doloremque molestias consectetur pariatur, corporis perspiciatis nulla ad incidunt beatae cupiditate minus ipsa porro ab laborum adipisci maiores earum dolores quod, id inventore explicabo aut! Iure sint labore, minima suscipit, animi, voluptatibus facilis architecto error rem nemo nobis? Nostrum ea possimus ipsam officiis quia at magnam est labore ipsum minima blanditiis, corrupti eum rerum, architecto asperiores vel cupiditate, modi hic rem. Fugiat fuga esse quo ratione fugit doloribus omnis repellendus veritatis illum dignissimos exercitationem dolorem, illo facilis, praesentium maiores. Ab voluptates sequi error rerum harum! Praesentium totam quas consequatur sed non id tempore pariatur, temporibus quidem delectus fugiat corrupti architecto facere sapiente aliquid sunt modi, voluptates qui velit et. Iure ipsam aspernatur voluptate molestiae qui, nihil est at atque vel consequuntur fugit, veritatis tempore sequi, assumenda suscipit inventore ratione deserunt error quasi voluptatem similique expedita. Modi dolor ipsum numquam nam praesentium, et eaque non excepturi amet accusantium!dignissimos exercitationem dolorem, illo facilis, praesentium maiores. Ab voluptates sequi error rerum harum! Praesentium totam quas consequatur sed non id tempore pariatur, temporibus quidem delectus fugiat corrupti architecto facere sapiente aliquid sunt modi, voluptates qui velit et. Iure ipsam aspernatur voluptate molestiae qui, nihil est at atque vel consequuntur fugit, veritatis tempore sequi, assumenda suscipit inventore ratione deserunt error quasi voluptatem similique expedita. Modi dolor ipsum numquam nam praesentium, et eaque non excepturi amet accusantium!",
    },
  ]);
}
